# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.13
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/content/post/

    steps:
      - checkout
      - run:
          name: install dependencies
          command: sudo pip install requests

      # generate post
      - run:
          name: generate post
          command: cd content/post/ && ls -lh && python generator.py && ls -lh
          
      # push to repo
      - run:
          name: git push
          command: |
            git config user.name "CircleCI Bot"
            git config user.email "bot@circleci.com"
            git add .
            git commit -m "Update docs"
            git push --force "https://${GITHUB_TOKEN}@github.com/DailyEng/source.git" master:master

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
